--  _   _                  _                 _
-- | | | |_   _ _ __  _ __| | __ _ _ __   __| |
-- | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
-- |  _  | |_| | |_) | |  | | (_| | | | | (_| |
-- |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
--        |___/|_|
--

-- Ensure we can find our local modules
package.path = package.path .. ";/home/tiizzel/.config/hypr/?.lua"

-- -----------------------------------------------------
-- Modules
-- -----------------------------------------------------
require("monitor")
require("autostart")
require("keybinds")
require("windowrules")
local colors = require("colors")

-- -----------------------------------------------------
-- Environments
-- -----------------------------------------------------
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("GDK_SCALE", "1")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("QS_NO_RELOAD_POPUP", "1")

-- -----------------------------------------------------
-- Cursor
-- -----------------------------------------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprctl setcursor breeze_cursors 24")
end)

hl.config({
    autogenerated = false,

    xwayland = {
        force_zero_scaling = true,
    },

    render = {
        direct_scanout = false,
    },

    -- -----------------------------------------------------
    -- Keyboard Layout
    -- -----------------------------------------------------
    input = {
        kb_layout = "de",
        numlock_by_default = true,
        follow_mouse = 1,
        mouse_refocus = false,
        touchpad = {
            natural_scroll = false,
            scroll_factor = 1.0,
            disable_while_typing = false,
        },
        sensitivity = 0,
    },

    -- -----------------------------------------------------
    -- General window layout and colors
    -- -----------------------------------------------------
    general = {
        gaps_in = 10,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = { colors = { colors.primary, colors.on_primary }, angle = 90 },
            inactive_border = colors.on_primary,
        },
        layout = "dwindle",
        resize_on_border = true,
        allow_tearing = true,
    },

    -- -----------------------------------------------------
    -- General window decoration
    -- -----------------------------------------------------
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 0.9,
        fullscreen_opacity = 1.0,

        blur = {
            enabled = true,
            size = 4,
            passes = 4,
            new_optimizations = true,
            ignore_opacity = true,
            xray = true,
        },

        shadow = {
            enabled = true,
            range = 32,
            render_power = 2,
            color = "rgba(00000050)",
        },
    },

    -- -----------------------------------------------------
    -- Layouts
    -- -----------------------------------------------------
    master = {
        -- new_status = "master"
    },

    binds = {
        workspace_back_and_forth = false,
        allow_workspace_cycles = true,
        pass_mouse_when_bound = false,
    },

    -- -----------------------------------------------------
    -- Misc settings
    -- -----------------------------------------------------
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        initial_workspace_tracking = 1,
        on_focus_under_fullscreen = true,
        allow_session_lock_restore = true,
    },
})

-- -----------------------------------------------------
-- Animations
-- -----------------------------------------------------
-- Use curves and animations helper functions for cleaner config
hl.curve("md3_standard", { type = "bezier", points = { {0.2, 0}, {0, 1} } })
hl.curve("md3_decel",    { type = "bezier", points = { {0.05, 0.7}, {0.1, 1} } })
hl.curve("md3_accel",    { type = "bezier", points = { {0.3, 0}, {0.8, 0.15} } })
hl.curve("menu_decel",   { type = "bezier", points = { {0.1, 1}, {0, 1} } })
hl.curve("menu_accel",   { type = "bezier", points = { {0.38, 0.04}, {1, 0.07} } })

hl.animation({ leaf = "windows",       enabled = true, speed = 3, bezier = "md3_decel", style = "popin 60%" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 3, bezier = "md3_decel", style = "popin 60%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 3, bezier = "md3_accel", style = "popin 60%" })
hl.animation({ leaf = "border",        enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3, bezier = "md3_decel" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 3, bezier = "menu_decel", style = "slide" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.6, bezier = "menu_accel" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 2, bezier = "menu_decel" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 4.5, bezier = "menu_accel" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 7, bezier = "menu_decel", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3, bezier = "md3_decel", style = "slidevert" })

