# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------

monitor = DP-1,5120x1440@240,auto,1, bitdepth, 10, cm, hdr, sdrbrightness, 1.33, sdrsaturation, 1.18
