[config]

[templates.colorsjson]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.config/hypr/colors/colors.json'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors-matugen.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
[templates.nwgdock]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/nwg-dock-hyprland/colors.css'

[templates.sequences]
input_path = '~/.config/matugen/templates/sequences'
output_path = '~/.cache/wal/sequences'

[templates.primary]
input_path = '~/.config/matugen/templates/primary'
output_path = '~/.config/hypr/colors/primary'

[templates.secondary]
input_path = '~/.config/matugen/templates/secondary'
output_path = '~/.config/hypr/colors/secondary'

[templates.on_surface]
input_path = '~/.config/matugen/templates/onsurface'
output_path = '~/.config/hypr/colors/onsurface'

[templates.on_primary]
input_path = '~/.config/matugen/templates/onprimary'
output_path = '~/.config/hypr/colors/onprimary'



[templates.quickshell_overview]
input_path  = "~/.config/matugen/templates/quickshell.qml"
output_path = "~/.config/quickshell/overview/common/Appearance.colors.qml"
post_hook = "quickshell ipc -c overview call overview forceReload"

[templates.ohmyposh]
input_path = '~/.config/matugen/templates/ohmyposh-colors.json'
output_path = '~/.config/ohmyposh/colors.json'
post_hook = "jq --slurpfile palette ~/.config/ohmyposh/colors.json '. + $palette[0]' ~/.config/ohmyposh/EDM115-newline.omp.json > /tmp/new_theme.json && mv /tmp/new_theme.json ~/.config/ohmyposh/EDM115-newline.omp.json"

[templates.firefox_chrome]
input_path = '~/.config/matugen/templates/firefox-userChrome.css'
output_path = '~/nixHypr/dotfiles/firefox/chrome/userChrome.css'

[templates.firefox_content]
input_path = '~/.config/matugen/templates/firefox-userContent.css'
output_path = '~/nixHypr/dotfiles/firefox/chrome/userContent.css'

[templates.zen_chrome]
input_path = '~/.config/matugen/templates/zen-userChrome.css'
output_path = '~/nixHypr/dotfiles/zen/chrome/userChrome.css'

[templates.zen_content]
input_path = '~/.config/matugen/templates/zen-userContent.css'
output_path = '~/nixHypr/dotfiles/zen/chrome/userContent.css'

[templates.zed]
input_path = 'templates/zed.json'
output_path = '~/nixHypr/dotfiles/zed/themes/matugen.json'

[templates.nixHypr_shell]
input_path = "~/.config/matugen/templates/quickshell.qml"
output_path = "~/nixHypr/dotfiles/hypr/scripts/quickshell/MatugenColors.qml"
post_hook = "quickshell ipc -c nixHypr-shell call main forceReload"

[templates.vesktop]
input_path = '~/.config/matugen/templates/vesktop.css'
output_path = '~/nixHypr/dotfiles/vesktop/matugen.css'

[templates.spicetify_css]
input_path = '~/.config/matugen/templates/spicetify-user.css'
output_path = '~/nixHypr/dotfiles/spicetify/Matugen/user.css'

[templates.spicetify_ini]
input_path = '~/.config/matugen/templates/spicetify-color.ini'
output_path = '~/nixHypr/dotfiles/spicetify/Matugen/color.ini'

[templates.antigravity]
input_path = '~/.config/matugen/templates/antigravity.json'
output_path = '~/nixHypr/dotfiles/antigravity/settings.json'

[templates.hyprland_colors_lua]
input_path = '~/.config/matugen/templates/colors.lua'
output_path = '~/nixHypr/dotfiles/hypr/colors.lua'
post_hook = 'hyprctl reload'
