# | Auto Start |
# autostart your favorite applications here

exec-once = systemctl --user start polkit-gnome-authentication-agent-1
exec-once = ~/.config/hypr/scripts/wallpaper.sh $(cat ~/.cache/quickshell/wallpaper/current_wallpaper 2>/dev/null || echo '~/Pictures/Wallpapers/default.jpg')
exec-once = quickshell -c nixHypr-shell
exec-once = quickshell -p ~/.config/quickshell/overview
exec-once = env PROFILE=com.nixHypr.dotfiles quickshell -p ~/.local/share/nixHypr-dotfiles-settings/quickshell
exec-once = ~/.config/hypr/scripts/gtk.sh
exec-once = hypridle
exec-once = wl-paste --watch cliphist store
exec-once = zen-beta
exec-once = vesktop
exec-once = spotify
exec-once = ~/.config/hypr/scripts/cleanup.sh
exec-once = ~/.config/com.nixHypr.hyprlandsettings/hyprctl.sh
