
$background = 0x11140fff

$error = 0xffb4abff

$error_container = 0x93000aff

$inverse_on_surface = 0x2e322bff

$inverse_primary = 0x406835ff

$inverse_surface = 0xe1e4daff

$on_background = 0xe1e4daff

$on_error = 0x690005ff

$on_error_container = 0xffdad6ff

$on_primary = 0x12380bff

$on_primary_container = 0xc1efafff

$on_primary_fixed = 0x012200ff

$on_primary_fixed_variant = 0x295020ff

$on_secondary = 0x263422ff

$on_secondary_container = 0xd7e8ccff

$on_secondary_fixed = 0x121f0eff

$on_secondary_fixed_variant = 0x3d4b37ff

$on_surface = 0xe1e4daff

$on_surface_variant = 0xc3c8bcff

$on_tertiary = 0x003739ff

$on_tertiary_container = 0xbcebeeff

$on_tertiary_fixed = 0x002021ff

$on_tertiary_fixed_variant = 0x1e4d50ff

$outline = 0x8d9387ff

$outline_variant = 0x43483fff

$primary = 0xa5d395ff

$primary_container = 0x295020ff

$primary_fixed = 0xc1efafff

$primary_fixed_dim = 0xa5d395ff

$scrim = 0x000000ff

$secondary = 0xbbcbb1ff

$secondary_container = 0x3d4b37ff

$secondary_fixed = 0xd7e8ccff

$secondary_fixed_dim = 0xbbcbb1ff

$shadow = 0x000000ff

$source_color = 0x283b22ff

$surface = 0x11140fff

$surface_bright = 0x363a34ff

$surface_container = 0x1d211bff

$surface_container_high = 0x272b25ff

$surface_container_highest = 0x32362fff

$surface_container_low = 0x191d17ff

$surface_container_lowest = 0x0c0f0aff

$surface_dim = 0x11140fff

$surface_tint = 0xa5d395ff

$surface_variant = 0x43483fff

$tertiary = 0xa0cfd2ff

$tertiary_container = 0x1e4d50ff

$tertiary_fixed = 0xbcebeeff

$tertiary_fixed_dim = 0xa0cfd2ff

