# | Rules |
# Window/Tag/Layer rules. | https://mangowm.github.io/docs/window-management/rules

windowrule = isfloating:1, appid:[Ss]team
windowrule = isfloating:0, title:Steam
windowrule = isfloating:1, appid:steam, title:Steam Settings

layerrule = noanim:1, noblur:1, layer_name:selection

# Opacity rules
windowrule = opacity:1.0:0.85, appid:^(.*)$
windowrule = opacity:0.90:0.85, appid:com.mitchellh.ghostty
windowrule = tags:1|2, istagsilent:1, appid:[Zz]en.*
windowrule = tags:2|4, istagsilent:1, appid:[Ss]potify.*
windowrule = tags:2|4, istagsilent:1, appid:[Vv]esktop.*
